# Generated by Django 5.2.13 on 2026-04-07 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listingimage_and_more'),
        ('trust', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('scam', 'Scam or fraud'), ('spam', 'Spam'), ('incorrect', 'Incorrect or misleading information')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing', '-created_at'], name='trust_listi_listing_77a556_idx'), models.Index(fields=['reason', '-created_at'], name='trust_listi_reason_39ef55_idx')],
                'constraints': [models.UniqueConstraint(fields=('reporter', 'listing'), name='unique_report_per_user_per_listing')],
            },
        ),
    ]
