# Generated by Django 5.2.13 on 2026-04-07 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0003_listingreport"),
    ]

    operations = []
