# Generated by Django 5.2.13 on 2026-04-07 22:37

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def dedupe_reviews_per_reviewer_seller(apps, schema_editor):
    """Keep newest review per (reviewer, seller); drop duplicates before new constraint."""
    Review = apps.get_model("trust", "Review")
    dup_pairs = (
        Review.objects.values("reviewer_id", "seller_id")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )
    for row in dup_pairs:
        qs = Review.objects.filter(
            reviewer_id=row["reviewer_id"],
            seller_id=row["seller_id"],
        ).order_by("-created_at", "-id")
        keep = qs.first()
        if keep:
            Review.objects.filter(
                reviewer_id=row["reviewer_id"],
                seller_id=row["seller_id"],
            ).exclude(pk=keep.pk).delete()


def dedupe_reviews_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_trust_score_and_flags"),
        ("trust", "0003_listingreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_reviews_per_reviewer_seller, dedupe_reviews_reverse),
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_per_listing_per_reviewer',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('reviewer', 'seller'), name='unique_review_per_reviewer_seller'),
        ),
    ]
