# Generated by Django 5.2.13 on 2026-04-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0004_trust_score_and_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingreport',
            name='reason',
            field=models.CharField(choices=[('scam', 'Estafa o fraude'), ('spam', 'Spam'), ('incorrect', 'Información incorrecta o engañosa')], db_index=True, max_length=20),
        ),
    ]
