# Generated by Django 5.0.4 on 2026-06-13 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_property_exact_location'),
        ('trust', '0005_alter_listingreport_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listingreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_reports_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Revisado'), ('actioned', 'Acción tomada'), ('dismissed', 'Descartado')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='listingreport',
            index=models.Index(fields=['status', '-created_at'], name='trust_listi_status_bddfd0_idx'),
        ),
    ]
