"""Curated electronics taxonomy for the Ecuador/Guayaquil market."""

from __future__ import annotations

from .market_taxonomy import FALLBACK_BRAND_NAME, FALLBACK_MODEL_NAME
from .models import ElectronicsItemType


# Curaduría 2026: señales de Mercado Libre Ecuador, retailers locales de
# Guayaquil y oferta común en marketplaces. Mantiene marcas/modelos frecuentes
# sin convertir el formulario en un catálogo exhaustivo.
_ELECTRONICS_OTROS_TAXONOMY: dict[str, list[str]] = {
    "Apple": [
        "iPhone 11",
        "iPhone 12",
        "iPhone 13",
        "iPhone 13 Pro",
        "iPhone 13 Pro Max",
        "iPhone 14",
        "iPhone 14 Pro",
        "iPhone 15",
        "iPhone 15 Pro Max",
        "iPhone 16",
        "iPhone 16 Pro Max",
        "iPad",
        "iPad Air",
        "iPad Pro",
        "MacBook Air",
        "MacBook Pro",
        "AirPods",
        "Apple Watch",
        "AirTag",
    ],
    "Samsung": [
        "Galaxy A05",
        "Galaxy A06",
        "Galaxy A15",
        "Galaxy A16",
        "Galaxy A24",
        "Galaxy A34",
        "Galaxy A54",
        "Galaxy A55",
        "Galaxy A56",
        "Galaxy S23",
        "Galaxy S24",
        "Galaxy S24 FE",
        "Galaxy S25",
        "Galaxy S25 Ultra",
        "Galaxy Tab A9",
        "Galaxy Watch",
        "Smart TV 55",
        "Smart TV 65",
        "Smart TV 70",
    ],
    "Xiaomi": [
        "Redmi A5",
        "Redmi 12",
        "Redmi 13",
        "Redmi 14C",
        "Redmi 15C",
        "Redmi Note 11",
        "Redmi Note 12",
        "Redmi Note 13",
        "Redmi Note 14",
        "Redmi Note 15",
        "Xiaomi 14T",
        "Xiaomi 14T Pro",
        "Xiaomi 15",
        "Redmi Buds",
        "Redmi Watch",
        "Mi Power Bank",
        "Mi TV Stick",
    ],
    "Huawei": [
        "P30 Lite",
        "P40 Lite",
        "Nova 9",
        "Nova 10",
        "Nova 11",
        "Nova Y70",
        "Nova Y90",
        "MatePad",
        "Watch GT",
        "FreeBuds",
    ],
    "Honor": [
        "Honor X5",
        "Honor X5c",
        "Honor X6",
        "Honor X7",
        "Honor X7d",
        "Honor X8",
        "Honor X8d",
        "Honor 90 Lite",
        "Honor 200",
        "Honor 400 Lite",
        "Honor 400 Pro",
    ],
    "Motorola": [
        "Moto E13",
        "Moto E14",
        "Moto G14",
        "Moto G24",
        "Moto G54",
        "Moto G84",
        "Moto Edge 40",
        "Moto Edge 50",
    ],
    "Oppo": [
        "A17",
        "A18",
        "A38",
        "A58",
        "A78",
        "Reno 8",
        "Reno 10",
        "Reno 11",
    ],
    "Realme": [
        "C53",
        "C55",
        "C67",
        "Note 50",
        "Realme 10",
        "Realme 11",
        "Realme 12",
    ],
    "Tecno": [
        "Spark 10",
        "Spark 20",
        "Spark Go",
        "Camon 20",
        "Camon 30",
        "Pova 5",
    ],
    "Infinix": [
        "Smart 8",
        "Hot 30",
        "Hot 40",
        "Note 30",
        "Note 40",
        "Zero 30",
    ],
    "HP": [
        "Pavilion",
        "Envy",
        "Victus",
        "Omen",
        "EliteBook",
        "ProBook",
        "DeskJet",
        "LaserJet",
    ],
    "Dell": [
        "Inspiron",
        "Latitude",
        "XPS",
        "Vostro",
        "Alienware",
        "OptiPlex",
    ],
    "Lenovo": [
        "IdeaPad",
        "IdeaPad 5",
        "ThinkPad",
        "Yoga",
        "Legion",
        "LOQ",
        "Tab M10",
    ],
    "Asus": [
        "VivoBook",
        "ZenBook",
        "TUF Gaming",
        "ROG Strix",
        "ROG Ally",
        "ExpertBook",
    ],
    "Acer": [
        "Aspire",
        "Swift",
        "Nitro 5",
        "Predator",
        "Chromebook",
    ],
    "MSI": [
        "Modern",
        "Katana",
        "Cyborg",
        "GF63",
        "Stealth",
    ],
    "LG": [
        "Smart TV 43",
        "Smart TV 55",
        "Smart TV 65",
        "OLED",
        "Sound Bar",
        "Monitor UltraGear",
    ],
    "Sony": [
        "PlayStation 4",
        "PlayStation 5",
        "DualSense",
        "Bravia 55",
        "Bravia 65",
        "WH-1000XM",
        "SRS Speaker",
    ],
    "Nintendo": [
        "Switch",
        "Switch OLED",
        "Switch Lite",
        "Joy-Con",
        "Pro Controller",
    ],
    "Microsoft": [
        "Xbox Series S",
        "Xbox Series X",
        "Xbox One",
        "Surface Pro",
        "Surface Laptop",
    ],
    "TCL": [
        "Smart TV 43",
        "Smart TV 50",
        "Smart TV 55",
        "Smart TV 65",
        "QLED",
    ],
    "Hisense": [
        "Smart TV 43",
        "Smart TV 50",
        "Smart TV 55",
        "Smart TV 65",
        "ULED",
    ],
    "JBL": [
        "Tune 510BT",
        "Tune 770NC",
        "Flip 6",
        "Charge 5",
        "Go 3",
        "Quantum",
    ],
    "Amazon": [
        "Echo Dot",
        "Echo Pop",
        "Fire TV Stick",
        "Fire TV Stick 4K",
        "Kindle",
    ],
    "TP-Link": [
        "Archer",
        "Deco",
        "Tapo C200",
        "Tapo C310",
        "Tapo C410",
        "RE200",
    ],
    "Logitech": [
        "Mouse M185",
        "Mouse MX Master",
        "Teclado K380",
        "Combo MK220",
        "Webcam C920",
        "Astro A10",
    ],
    "Epson": [
        "EcoTank L3250",
        "EcoTank L4260",
        "L121",
        "PowerLite",
        "Proyector",
    ],
    "Kingston": [
        "DataTraveler 64GB",
        "DataTraveler 128GB",
        "SSD A400",
        "NV2 SSD",
        "Memoria RAM",
    ],
    FALLBACK_BRAND_NAME: [FALLBACK_MODEL_NAME],
}

# Taxonomía por tipo de producto (patrón unificado con hogar).
ELECTRONICS_TYPE_MARKET_TAXONOMY: dict[str, dict[str, list[str]]] = {
    ElectronicsItemType.CELULARES: {
        "Apple": [
            "iPhone 11",
            "iPhone 12",
            "iPhone 13",
            "iPhone 13 Pro",
            "iPhone 13 Pro Max",
            "iPhone 14",
            "iPhone 14 Pro",
            "iPhone 15",
            "iPhone 15 Pro Max",
            "iPhone 16",
            "iPhone 16 Pro Max",
            "iPhone 17",
            "iPhone 17 Pro",
        ],
        "Samsung": [
            "Galaxy A05",
            "Galaxy A06",
            "Galaxy A15",
            "Galaxy A16",
            "Galaxy A24",
            "Galaxy A34",
            "Galaxy A54",
            "Galaxy A55",
            "Galaxy A56",
            "Galaxy S23",
            "Galaxy S24",
            "Galaxy S24 FE",
            "Galaxy S25",
            "Galaxy S25 Ultra",
        ],
        "Xiaomi": [
            "Redmi A5",
            "Redmi 12",
            "Redmi 13",
            "Redmi 14C",
            "Redmi 15C",
            "Redmi Note 11",
            "Redmi Note 12",
            "Redmi Note 13",
            "Redmi Note 14",
            "Redmi Note 15",
            "Xiaomi 14T",
            "Xiaomi 14T Pro",
            "Xiaomi 15",
        ],
        "Honor": [
            "Honor X5",
            "Honor X5c",
            "Honor X7",
            "Honor X7d",
            "Honor X8",
            "Honor X8d",
            "Honor 90 Lite",
            "Honor 200",
            "Honor 400 Lite",
            "Honor 400 Pro",
        ],
        "Huawei": [
            "P30 Lite",
            "P40 Lite",
            "Nova 9",
            "Nova 10",
            "Nova 11",
            "Nova Y70",
            "Nova Y90",
        ],
        "Motorola": [
            "Moto E13",
            "Moto E14",
            "Moto G14",
            "Moto G24",
            "Moto G54",
            "Moto G84",
            "Moto Edge 40",
            "Moto Edge 50",
        ],
        "Oppo": ["A17", "A18", "A38", "A58", "A78", "Reno 10", "Reno 11"],
        "Realme": ["C53", "C55", "C67", "Note 50", "Realme 11", "Realme 12"],
        "Tecno": ["Spark 10", "Spark 20", "Spark Go", "Camon 20", "Camon 30"],
        "Infinix": ["Smart 8", "Hot 30", "Hot 40", "Note 30", "Note 40"],
        "ZTE": ["A56", "A56 Pro", "Blade A54", "Blade V50"],
        "Nubia": ["Air", "Neo 2", "Focus Pro"],
        "Cat": ["S62", "S75"],
        FALLBACK_BRAND_NAME: [FALLBACK_MODEL_NAME],
    },
    ElectronicsItemType.LAPTOPS_COMPUTADORAS: {
        "HP": ["Pavilion", "Envy", "Victus", "Omen", "EliteBook", "ProBook"],
        "Dell": ["Inspiron", "Latitude", "XPS", "Vostro", "Alienware", "OptiPlex"],
        "Lenovo": ["IdeaPad", "IdeaPad 5", "ThinkPad", "Yoga", "Legion", "LOQ"],
        "Asus": ["VivoBook", "ZenBook", "TUF Gaming", "ROG Strix", "ROG Ally"],
        "Acer": ["Aspire", "Swift", "Nitro 5", "Predator", "Chromebook"],
        "MSI": ["Modern", "Katana", "Cyborg", "GF63", "Stealth"],
        "Apple": ["MacBook Air", "MacBook Pro", "iMac", "Mac Mini"],
        "Gigabyte": ["G5", "G6", "Aorus"],
        "Intel": ["Core i3", "Core i5", "Core i7", "Core i9"],
        "AMD": ["Ryzen 3", "Ryzen 5", "Ryzen 7", "Ryzen 9"],
        FALLBACK_BRAND_NAME: [FALLBACK_MODEL_NAME],
    },
    ElectronicsItemType.TV_AUDIO_VIDEO: {
        "Samsung": ["Smart TV 43", "Smart TV 50", "Smart TV 55", "Smart TV 65", "Smart TV 70", "QLED 55", "QLED 65"],
        "LG": ["Smart TV 43", "Smart TV 55", "Smart TV 65", "OLED", "Sound Bar"],
        "TCL": ["Smart TV 43", "Smart TV 50", "Smart TV 55", "Smart TV 65", "QLED"],
        "Hisense": ["Smart TV 43", "Smart TV 50", "Smart TV 55", "Smart TV 65", "ULED"],
        "Sony": ["Bravia 55", "Bravia 65", "WH-1000XM", "SRS Speaker"],
        "Riviera": ["Smart TV 32", "Smart TV 43", "Smart TV 55"],
        "Indurama": ["QLED 55", "QLED 65", "Mini LED 100"],
        "Xiaomi": ["Mi TV Stick", "TV Box S", "Redmi Buds", "Soundbar"],
        "Amazon": ["Echo Dot", "Echo Pop", "Fire TV Stick", "Fire TV Stick 4K"],
        "JBL": ["Tune 510BT", "Tune 770NC", "Flip 6", "Charge 5", "Go 3"],
        "Onn": ["TV Stick Full HD", "TV Box 4K"],
        "Roku": ["Express", "Streaming Stick 4K"],
        FALLBACK_BRAND_NAME: [FALLBACK_MODEL_NAME],
    },
    ElectronicsItemType.CONSOLAS_VIDEOJUEGOS: {
        "Sony": ["PlayStation 4", "PlayStation 4 Pro", "PlayStation 5", "PlayStation 5 Slim", "DualSense"],
        "Microsoft": ["Xbox One", "Xbox Series S", "Xbox Series X", "Control Xbox"],
        "Nintendo": ["Switch", "Switch OLED", "Switch Lite", "Joy-Con", "Pro Controller"],
        "Logitech": ["G29", "G923", "Astro A10"],
        FALLBACK_BRAND_NAME: [FALLBACK_MODEL_NAME],
    },
    ElectronicsItemType.TABLETS_WEARABLES: {
        "Apple": ["iPad", "iPad Air", "iPad Pro", "iPad mini", "Apple Watch", "AirPods", "AirTag"],
        "Samsung": ["Galaxy Tab A9", "Galaxy Tab S9", "Galaxy Tab S10", "Galaxy Watch", "Galaxy Buds"],
        "Xiaomi": ["Redmi Pad", "Xiaomi Pad 6", "Redmi Watch", "Redmi Buds"],
        "Huawei": ["MatePad", "Watch GT", "FreeBuds"],
        "Lenovo": ["Tab M9", "Tab M10", "Tab P11"],
        "Amazon": ["Kindle", "Kindle Paperwhite", "Fire HD"],
        "Honor": ["Pad X8", "Pad 9", "Watch"],
        FALLBACK_BRAND_NAME: [FALLBACK_MODEL_NAME],
    },
    ElectronicsItemType.CAMARAS_SEGURIDAD: {
        "TP-Link": ["Tapo C200", "Tapo C210", "Tapo C310", "Tapo C410", "Tapo C500"],
        "EZVIZ": ["H3", "C6N", "C8C", "BC1C"],
        "Hikvision": ["Domo 2MP", "Bullet 2MP", "DVR 4 canales", "DVR 8 canales"],
        "Dahua": ["Domo 2MP", "Bullet 2MP", "DVR 4 canales", "NVR 8 canales"],
        "Xiaomi": ["Mi Home Security Camera", "Outdoor Camera"],
        "Imou": ["Ranger 2", "Bullet 2C", "Cue 2"],
        "3NStar": ["Scanner SC415BT", "Cámara IP"],
        FALLBACK_BRAND_NAME: [FALLBACK_MODEL_NAME],
    },
    ElectronicsItemType.IMPRESORAS_MONITORES: {
        "Epson": ["EcoTank L121", "EcoTank L3250", "EcoTank L4260", "PowerLite", "Proyector"],
        "HP": ["DeskJet", "Ink Tank", "Smart Tank", "LaserJet", "Monitor 24"],
        "Canon": ["PIXMA G3110", "PIXMA G3160", "ImageCLASS"],
        "Brother": ["DCP-T220", "DCP-T420W", "HL-L2320D"],
        "Samsung": ["Monitor 24", "Monitor 27", "Odyssey"],
        "LG": ["Monitor 24", "Monitor 27", "UltraGear", "UltraWide"],
        "AOC": ["Monitor 22", "Monitor 24", "Monitor 27", "Gaming"],
        "Dell": ["Monitor 24", "Monitor 27", "UltraSharp"],
        FALLBACK_BRAND_NAME: [FALLBACK_MODEL_NAME],
    },
    ElectronicsItemType.REDES_ACCESORIOS: {
        "TP-Link": ["Archer", "Deco", "RE200", "RE305", "Switch 5 puertos"],
        "Kingston": ["DataTraveler 64GB", "DataTraveler 128GB", "SSD A400", "NV2 SSD", "Memoria RAM"],
        "Logitech": ["Mouse M185", "Mouse MX Master", "Teclado K380", "Combo MK220", "Webcam C920"],
        "Xiaomi": ["Mi Power Bank", "Cable USB-C", "Cargador 33W", "Cargador 67W"],
        "Sandisk": ["Ultra 64GB", "Ultra 128GB", "Extreme microSD"],
        "Western Digital": ["Disco duro 1TB", "Disco duro 2TB", "WD Green SSD"],
        "Seagate": ["Expansion 1TB", "Expansion 2TB", "Barracuda"],
        "Ubiquiti": ["UniFi AP", "NanoStation", "LiteBeam"],
        FALLBACK_BRAND_NAME: [FALLBACK_MODEL_NAME],
    },
    ElectronicsItemType.OTROS: _ELECTRONICS_OTROS_TAXONOMY,
}
