"""Curated home goods taxonomy for the Ecuador/Guayaquil market."""

from __future__ import annotations

from .market_taxonomy import FALLBACK_BRAND_NAME, FALLBACK_MODEL_NAME
from .models import HomeItemType

# Curaduría 2026: opciones comunes en clasificados y retailers ecuatorianos
# para hogar en Guayaquil. Mantiene listas cortas para no saturar el formulario.
HOMEGOODS_TYPE_MARKET_TAXONOMY: dict[str, dict[str, list[str]]] = {
    HomeItemType.FURNITURE: {
        "Colineal": [
            "Sofá 3 puestos",
            "Seccional",
            "Recliner Texas",
            "Recliner Rosia",
            "Sala Bombay",
            "Mesa de comedor",
            "Centro de entretenimiento",
        ],
        "Muebles El Bosque": [
            "Juego de sala",
            "Comedor 6 puestos",
            "Dormitorio",
            "Closet",
            "Mueble de TV",
        ],
        "Ashley": [
            "Sofá reclinable",
            "Seccional",
            "Comedor",
            "Cama tapizada",
            "Reclinable",
        ],
        "Pycca": [
            "Estantería",
            "Mesa auxiliar",
            "Silla",
            "Organizador",
            "Zapatera",
        ],
        "Sukasa": ["Sofá", "Butaca", "Mesa lateral", "Consola", "Comedor"],
        "Tempo Design": [
            "Sofá",
            "Seccional",
            "Comedor",
            "Dormitorio",
            "Mueble de TV",
        ],
        "Ecoline": ["Mesa de comedor", "Silla", "Rack TV", "Mesa de centro"],
        "IKEA": ["Kallax", "Malm", "Billy", "Lack"],
        "Artesanal / local": ["Sofá", "Comedor", "Cama", "Mueble de TV"],
        FALLBACK_BRAND_NAME: [FALLBACK_MODEL_NAME],
    },
    HomeItemType.APPLIANCES: {
        "Indurama": [
            "RI-289",
            "RI-380 Avant Plus",
            "RI-395 Quarzo",
            "RI-425 Quarzo",
            "RI-475 Quarzo",
            "LRI-19DGR",
            "LRI-15BLSA",
            "Mónaco Zafiro",
            "Pamplona Quarzo",
            "Galicia Zafiro",
            "MWI-20CR",
            "HTI-10",
        ],
        "Mabe": [
            "RMA313FXEU",
            "RMP389JEG",
            "RMP415HEU",
            "RMP470YEU",
            "MSE521QMLSS0",
            "LME9120WDGAB",
            "LMDX6124",
            "EM6060FX3",
            "EM7630FX0",
            "EM7640FX1",
            "SMG47N8MSBAB0",
            "MMT12CDBWCC",
        ],
        "LG": [
            "TurboDrum 16 kg",
            "TurboDrum 19 kg",
            "Smart Inverter",
            "Inverter Direct Drive",
            "Side by Side",
            "InstaView",
            "NeoChef",
            "Dual Inverter",
        ],
        "Samsung": [
            "Digital Inverter",
            "Ecobubble",
            "No Frost",
            "Side by Side",
            "Microondas Grill",
            "WindFree",
        ],
        "Whirlpool": [
            "Xpert Inverter",
            "WRM56 Top Mount",
            "WRW32 con dispensador",
            "Lavadora 16 kg",
            "Microondas con grill",
            "Secadora",
        ],
        "Electrolux": [
            "Refrigeradora Top Freezer",
            "Lavadora 16 kg",
            "Aspiradora",
            "Microondas",
            "Cafetera Experience",
        ],
        "Riviera": [
            "Aire acondicionado 12000 BTU",
            "Aire acondicionado 18000 BTU",
            "Aire acondicionado 24000 BTU",
            "Smart TV 43",
        ],
        "RCA": [
            "Congelador horizontal",
            "Minibar",
            "Aire acondicionado 12000 BTU",
            "Aire acondicionado 36000 BTU",
        ],
        "TCL": [
            "Refrigeradora P650",
            "Aire acondicionado",
            "Smart TV 43",
            "Smart TV 55",
        ],
        "Ecoline": [
            "Refrigeradora 243L",
            "Refrigeradora 271L",
            "Cocina Constanza",
            "Cocina Domenica",
        ],
        "Oster": [
            "Air Fryer 4L",
            "Air Fryer 5.5L",
            "Horno freidora 25L",
            "Licuadora clásica",
            "Horno tostador",
            "Cafetera",
            "Sanduchera",
        ],
        "Black+Decker": [
            "Air Fryer",
            "Licuadora",
            "Plancha",
            "Aspiradora",
            "Horno tostador",
        ],
        "Hamilton Beach": ["Licuadora", "Cafetera", "Procesador", "Horno tostador"],
        "Ninja": ["Air Fryer", "Licuadora", "Granizadora", "Freidora Dual Zone"],
        "Echef": ["Air Fryer AF815DT", "Freidora de aire 5L"],
        "Imaco": ["Licuadora", "Plancha", "Ventilador", "Sanduchera"],
        FALLBACK_BRAND_NAME: [FALLBACK_MODEL_NAME],
    },
    HomeItemType.DECOR: {
        "Pycca": [
            "Lámpara",
            "Espejo",
            "Cuadro decorativo",
            "Alfombra",
            "Cortina",
            "Florero",
        ],
        "Sukasa": [
            "Lámpara de piso",
            "Espejo",
            "Centro de mesa",
            "Jarrón",
            "Alfombra",
        ],
        "De Prati Hogar": [
            "Cortinas",
            "Alfombra",
            "Cojines",
            "Set decorativo",
            "Ropa de cama",
        ],
        "Home Vega": ["Lámpara", "Espejo", "Repisa", "Cuadro", "Organizador"],
        "Colineal": ["Lámpara", "Alfombra", "Cojines", "Set de dormitorio"],
        "Boyacá": ["Lámpara", "Espejo", "Repisa", "Cortina"],
        "TodoHogar": ["Organizador", "Lámpara", "Alfombra", "Set de baño"],
        "Artesanal / local": [
            "Cuadro",
            "Jarrón",
            "Figura decorativa",
            "Canasto",
            "Macramé",
        ],
        FALLBACK_BRAND_NAME: [FALLBACK_MODEL_NAME],
    },
    HomeItemType.KITCHENWARE: {
        "Tramontina": [
            "Batería de ollas",
            "Juego de cuchillos",
            "Sartén",
            "Cubiertos",
            "Olla de presión",
        ],
        "Oster": [
            "Licuadora",
            "Procesador",
            "Cafetera",
            "Horno tostador",
            "Sanduchera",
        ],
        "Umco": [
            "Olla arrocera",
            "Sartén",
            "Olla de presión",
            "Batería de cocina",
            "Caldero",
        ],
        "Pycca": [
            "Vajilla",
            "Juego de vasos",
            "Organizador",
            "Set de cocina",
            "Repostero",
        ],
        "Tupperware": ["Set hermético", "Lonchera", "Organizador", "Jarra", "Contenedor"],
        "Hamilton Beach": ["Licuadora", "Cafetera", "Procesador", "Batidora"],
        "Ninja": ["Licuadora", "Air Fryer", "Procesador", "Granizadora"],
        "Imaco": ["Licuadora", "Sanduchera", "Olla arrocera", "Plancha"],
        "Record": ["Olla de presión", "Batería de ollas", "Sartén"],
        FALLBACK_BRAND_NAME: [FALLBACK_MODEL_NAME],
    },
    HomeItemType.MATTRESSES_BEDS: {
        "Chaide": [
            "Imperial",
            "Continental de Lujo",
            "Zafiro",
            "Ortopédico",
            "Base tapiz",
            "Queen",
            "King",
        ],
        "Paraíso": [
            "Classic",
            "Flex",
            "Comfort",
            "Excellence",
            "Pocket Bamboo",
            "Sensaciones",
            "Queen",
            "King",
        ],
        "Rosen": ["New Style", "Ergo T", "Art 4", "Queen", "King"],
        "Simmons": ["Beautyrest", "BackCare", "Queen", "King"],
        "Resiflex": ["Ortopédico", "Pillow Top", "Queen", "King"],
        "Colineal": [
            "Cama 2 plazas",
            "Cama queen",
            "Cabecera",
            "Base",
            "Sofá cama",
        ],
        "Dormilón": ["Ortopédico", "Pillow Top", "Queen", "King"],
        FALLBACK_BRAND_NAME: [FALLBACK_MODEL_NAME],
    },
    HomeItemType.OUTDOOR_GARDEN: {
        "Tramontina": [
            "Mesa plegable",
            "Sillas plásticas",
            "Banco jardín",
            "Parrilla",
            "Macetero",
        ],
        "Keter": [
            "Bodega exterior",
            "Organizador",
            "Silla jardín",
            "Mesa exterior",
            "Baúl exterior",
        ],
        "Pycca": [
            "Juego de patio",
            "Macetero",
            "Silla exterior",
            "Sombrilla",
            "Parrilla",
        ],
        "Rubbermaid": ["Organizador", "Contenedor", "Bodega exterior", "Basurero"],
        "Coleman": ["Cooler", "Silla plegable", "Carpa", "Mesa camping"],
        "Bestway": ["Piscina inflable", "Colchón inflable", "Jacuzzi inflable"],
        "Intex": ["Piscina inflable", "Colchón inflable", "Filtro piscina"],
        "Weber": ["Parrilla carbón", "Parrilla gas", "Accesorios BBQ"],
        "Artesanal / local": [
            "Juego de patio",
            "Mesa exterior",
            "Macetero",
            "Parrilla",
            "Banca",
        ],
        FALLBACK_BRAND_NAME: [FALLBACK_MODEL_NAME],
    },
}
