# Generated by Django 5.2.13 on 2026-04-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listingimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False, help_text='Set when multiple users report this listing.'),
        ),
    ]
