# Generated by Django 5.2.13 on 2026-04-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_trust_score_and_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], db_index=True, default='draft', max_length=20),
        ),
    ]
