# Generated by Django 5.2.13 on 2026-04-09 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento')], max_length=20, verbose_name='Tipo')),
                ('rooms', models.PositiveSmallIntegerField(verbose_name='Habitaciones')),
                ('bathrooms', models.PositiveSmallIntegerField(verbose_name='Baños')),
                ('area_m2', models.PositiveIntegerField(verbose_name='Superficie (m²)')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='listings.listing')),
            ],
            options={
                'indexes': [models.Index(fields=['listing'], name='listings_pr_listing_5747e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80, verbose_name='Modelo')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('doors', models.PositiveSmallIntegerField(verbose_name='Puertas')),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático'), ('cvt', 'CVT'), ('otro', 'Otro / no especificado')], max_length=20, verbose_name='Transmisión')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='listings.listing')),
            ],
            options={
                'indexes': [models.Index(fields=['listing'], name='listings_ve_listing_a4abb9_idx')],
            },
        ),
    ]
