# Generated by Django 5.0.4 on 2026-04-09 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_vehicle_property_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicsListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=120, verbose_name='Modelo')),
                ('condition', models.CharField(choices=[('nuevo', 'Nuevo / nueva'), ('usado', 'Usado / usada')], max_length=10, verbose_name='Condición')),
                ('warranty', models.BooleanField(default=False, verbose_name='Tiene garantía vigente')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electronics', to='listings.listing')),
            ],
            options={
                'indexes': [models.Index(fields=['listing'], name='listings_el_listing_8e6929_idx')],
            },
        ),
        migrations.CreateModel(
            name='HomeGoodsListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('nuevo', 'Nuevo / nueva'), ('usado', 'Usado / usada')], max_length=10, verbose_name='Condición')),
                ('material', models.CharField(blank=True, max_length=120)),
                ('dimensions', models.CharField(blank=True, max_length=120, verbose_name='Dimensiones aprox.')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homegoods', to='listings.listing')),
            ],
            options={
                'indexes': [models.Index(fields=['listing'], name='listings_ho_listing_1e1b1e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MotorcycleListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('engine_cc', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cilindrada (cc)')),
                ('condition', models.CharField(choices=[('nuevo', 'Nuevo / nueva'), ('usado', 'Usado / usada')], max_length=10, verbose_name='Condición')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motorcycle', to='listings.listing')),
            ],
            options={
                'indexes': [models.Index(fields=['listing'], name='listings_mo_listing_0b5731_idx')],
            },
        ),
    ]
