# Generated by Django 5.0.4 on 2026-04-10 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_vehiclebrand_vehiclemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelisting',
            name='brand_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_listings', to='listings.vehiclebrand'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('hibrido', 'Híbrido'), ('electrico', 'Eléctrico')], max_length=20, verbose_name='Combustible'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='model_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_listings', to='listings.vehiclemodel'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['brand_fk', 'model_fk'], name='listings_ve_brand_f_e4dd35_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['year'], name='listings_ve_year_2f6127_idx'),
        ),
    ]
