# Generated by GPT-5.2 on 2026-04-10

from __future__ import annotations

from django.db import migrations
from django.utils.text import slugify


def _unique_slug(Model, base_slug: str) -> str:
    base = base_slug or "item"
    slug = base
    n = 0
    while Model.objects.filter(slug=slug).exists():
        n += 1
        slug = f"{base}-{n}"
    return slug


def backfill_vehicle_brand_model_fk(apps, schema_editor):
    VehicleListing = apps.get_model("listings", "VehicleListing")
    VehicleBrand = apps.get_model("listings", "VehicleBrand")
    VehicleModel = apps.get_model("listings", "VehicleModel")

    qs = VehicleListing.objects.all().only("id", "brand", "model", "brand_fk_id", "model_fk_id")

    for row in qs.iterator(chunk_size=500):
        if row.brand_fk_id and row.model_fk_id:
            continue

        brand_raw = (row.brand or "").strip()
        model_raw = (row.model or "").strip()
        if not brand_raw or not model_raw:
            continue

        brand_name = brand_raw.title()
        brand_slug_base = slugify(brand_name)[:50] or slugify(brand_raw)[:50]
        brand_obj = VehicleBrand.objects.filter(name=brand_name).first()
        if not brand_obj:
            brand_obj = VehicleBrand.objects.create(
                name=brand_name,
                slug=_unique_slug(VehicleBrand, brand_slug_base),
            )

        model_name = model_raw.title()
        model_slug_base = slugify(model_name)[:60] or slugify(model_raw)[:60]
        model_obj = VehicleModel.objects.filter(brand=brand_obj, name=model_name).first()
        if not model_obj:
            model_obj = VehicleModel.objects.create(
                brand=brand_obj,
                name=model_name,
                slug=model_slug_base or _unique_slug(VehicleModel, f"{brand_obj.slug}-{model_slug_base}"),
            )

        VehicleListing.objects.filter(pk=row.pk).update(
            brand_fk=brand_obj,
            model_fk=model_obj,
        )


def noop_reverse(apps, schema_editor):
    # Backward-compatible: keep generated taxonomy rows.
    return


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0009_vehiclelisting_brand_fk_vehiclelisting_fuel_type_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_vehicle_brand_model_fk, reverse_code=noop_reverse),
    ]

