# Generated by GPT-5.2 on 2026-04-10

from __future__ import annotations

from django.db import migrations
from django.utils.text import slugify


def seed_vehicle_taxonomy_minimal(apps, schema_editor):
    VehicleBrand = apps.get_model("listings", "VehicleBrand")
    VehicleModel = apps.get_model("listings", "VehicleModel")

    if VehicleBrand.objects.exists():
        return

    taxonomy: dict[str, list[str]] = {
        "Toyota": ["Corolla", "Yaris", "RAV4", "Hilux"],
        "Chevrolet": ["Spark", "Aveo", "Tracker", "D-Max"],
        "Kia": ["Rio", "Sportage", "Seltos", "Picanto"],
        "Hyundai": ["Tucson", "Elantra", "Accent", "Santa Fe"],
        "Nissan": ["Versa", "Sentra", "Kicks", "X-Trail"],
    }

    for brand_name, models in taxonomy.items():
        brand = VehicleBrand.objects.create(
            name=brand_name,
            slug=slugify(brand_name),
        )
        for model_name in models:
            VehicleModel.objects.create(
                brand=brand,
                name=model_name,
                slug=slugify(model_name),
            )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0010_backfill_vehicle_brand_model_fk"),
    ]

    operations = [
        migrations.RunPython(seed_vehicle_taxonomy_minimal, reverse_code=noop_reverse),
    ]

