# Generated by Django 5.0.4 on 2026-04-10 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_propertylisting_professional_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='propertylisting',
            new_name='listings_pr_propert_dc1e5b_idx',
            old_name='listings_pr_propert_idx',
        ),
        migrations.RenameIndex(
            model_name='propertylisting',
            new_name='listings_pr_operati_3f2012_idx',
            old_name='listings_pr_operati_idx',
        ),
        migrations.RenameIndex(
            model_name='propertylisting',
            new_name='listings_pr_area_m2_f67e83_idx',
            old_name='listings_pr_area_m2_idx',
        ),
    ]
