# Generated by Django 5.0.4 on 2026-04-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_motorcyclelisting_filters_and_specs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='motorcyclelisting',
            new_name='listings_mo_year_e31ef2_idx',
            old_name='listings_mo_year_idx',
        ),
        migrations.RenameIndex(
            model_name='motorcyclelisting',
            new_name='listings_mo_brand_cda67f_idx',
            old_name='listings_mo_brand_idx',
        ),
        migrations.RenameIndex(
            model_name='motorcyclelisting',
            new_name='listings_mo_model_dbccd0_idx',
            old_name='listings_mo_model_idx',
        ),
    ]
