# Generated by Django 5.0.4 on 2026-04-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_rename_listings_mo_year_idx_listings_mo_year_e31ef2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicslisting',
            name='specs_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='electronicslisting',
            name='warranty_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Meses de garantía'),
        ),
        migrations.AlterField(
            model_name='electronicslisting',
            name='condition',
            field=models.CharField(choices=[('nuevo', 'Nuevo / nueva'), ('usado', 'Usado / usada'), ('refurbished', 'Reacondicionado')], max_length=20, verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='homegoodslisting',
            name='condition',
            field=models.CharField(choices=[('nuevo', 'Nuevo / nueva'), ('usado', 'Usado / usada'), ('refurbished', 'Reacondicionado')], max_length=20, verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='motorcyclelisting',
            name='condition',
            field=models.CharField(choices=[('nuevo', 'Nuevo / nueva'), ('usado', 'Usado / usada'), ('refurbished', 'Reacondicionado')], max_length=20, verbose_name='Condición'),
        ),
        migrations.AddIndex(
            model_name='electronicslisting',
            index=models.Index(fields=['brand'], name='listings_el_brand_3206af_idx'),
        ),
    ]
