# Generated by Django 5.0.4 on 2026-04-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_electronics_contract_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='homegoodslisting',
            name='brand',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homegoodslisting',
            name='item_type',
            field=models.CharField(blank=True, choices=[('furniture', 'Muebles'), ('appliances', 'Electrodomésticos / cocina'), ('decor', 'Decoración')], max_length=20, verbose_name='Tipo de artículo'),
        ),
        migrations.AddField(
            model_name='homegoodslisting',
            name='specs_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='homegoodslisting',
            index=models.Index(fields=['item_type'], name='listings_ho_item_ty_cd38e8_idx'),
        ),
    ]
