# Generated by Django 5.2.13 on 2026-04-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_listing_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to='listings/%Y/%m/variants/'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to='listings/%Y/%m/variants/'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='listings/%Y/%m/variants/'),
        ),
    ]
