# Generated by Django 5.2.13 on 2026-04-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_listingimage_image_large_listingimage_image_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='image_large_webp',
            field=models.ImageField(blank=True, null=True, upload_to='listings/%Y/%m/variants/'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_medium_webp',
            field=models.ImageField(blank=True, null=True, upload_to='listings/%Y/%m/variants/'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_thumb_webp',
            field=models.ImageField(blank=True, null=True, upload_to='listings/%Y/%m/variants/'),
        ),
    ]
