# Generated by Django 5.0.4 on 2026-06-11 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_listing_published_by_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_slug', models.SlugField(max_length=32)),
                ('item_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['brand__name', 'sort_order', 'name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='electronicslisting',
            name='listings_el_brand_3206af_idx',
        ),
        migrations.RemoveIndex(
            model_name='motorcyclelisting',
            name='listings_mo_brand_cda67f_idx',
        ),
        migrations.RemoveIndex(
            model_name='motorcyclelisting',
            name='listings_mo_model_dbccd0_idx',
        ),
        migrations.RemoveField(
            model_name='electronicslisting',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='electronicslisting',
            name='model',
        ),
        migrations.RemoveField(
            model_name='homegoodslisting',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='motorcyclelisting',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='motorcyclelisting',
            name='model',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='model',
        ),
        migrations.AddField(
            model_name='electronicslisting',
            name='item_type',
            field=models.CharField(blank=True, choices=[('celulares', 'Celulares'), ('laptops_computadoras', 'Laptops y computadoras'), ('tv_audio_video', 'TV, audio y video'), ('consolas_videojuegos', 'Consolas y videojuegos'), ('tablets_wearables', 'Tablets y wearables'), ('camaras_seguridad', 'Cámaras y seguridad'), ('impresoras_monitores', 'Impresoras y monitores'), ('redes_accesorios', 'Redes y accesorios'), ('otros', 'Otros electrónicos')], max_length=32, verbose_name='Tipo de producto'),
        ),
        migrations.AlterField(
            model_name='homegoodslisting',
            name='item_type',
            field=models.CharField(blank=True, choices=[('furniture', 'Muebles'), ('appliances', 'Electrodomésticos / cocina'), ('decor', 'Decoración'), ('kitchenware', 'Menaje y cocina'), ('mattresses_beds', 'Colchones y camas'), ('outdoor_garden', 'Patio y jardín')], max_length=20, verbose_name='Tipo de artículo'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('venta', 'Venta'), ('alquiler', 'Alquiler'), ('alquiler_temporal', 'Alquiler temporal')], max_length=20, null=True, verbose_name='Operación'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='property_type',
            field=models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('suite', 'Suite'), ('terreno_lote', 'Terreno / Lote'), ('oficina_comercial', 'Oficina comercial'), ('local_comercial', 'Local comercial'), ('bodega_galpon', 'Bodega / Galpón'), ('hacienda_quinta', 'Hacienda / Quinta'), ('habitacion', 'Habitación')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='electronicslisting',
            name='brand_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electronics_listings', to='listings.marketbrand'),
        ),
        migrations.AddField(
            model_name='homegoodslisting',
            name='brand_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homegoods_listings', to='listings.marketbrand'),
        ),
        migrations.AddField(
            model_name='motorcyclelisting',
            name='brand_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motorcycle_listings', to='listings.marketbrand'),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='brand_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_listings', to='listings.marketbrand'),
        ),
        migrations.AddField(
            model_name='marketmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='listings.marketbrand'),
        ),
        migrations.AddField(
            model_name='electronicslisting',
            name='model_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electronics_listings', to='listings.marketmodel'),
        ),
        migrations.AddField(
            model_name='homegoodslisting',
            name='model_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homegoods_listings', to='listings.marketmodel'),
        ),
        migrations.AddField(
            model_name='motorcyclelisting',
            name='model_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motorcycle_listings', to='listings.marketmodel'),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='model_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_listings', to='listings.marketmodel'),
        ),
        migrations.AddIndex(
            model_name='electronicslisting',
            index=models.Index(fields=['item_type'], name='listings_el_item_ty_23404b_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicslisting',
            index=models.Index(fields=['brand_fk', 'model_fk'], name='listings_el_brand_f_d838b8_idx'),
        ),
        migrations.AddIndex(
            model_name='homegoodslisting',
            index=models.Index(fields=['brand_fk', 'model_fk'], name='listings_ho_brand_f_adbfaf_idx'),
        ),
        migrations.AddIndex(
            model_name='motorcyclelisting',
            index=models.Index(fields=['brand_fk', 'model_fk'], name='listings_mo_brand_f_4e7ba2_idx'),
        ),
        migrations.DeleteModel(
            name='VehicleBrand',
        ),
        migrations.AddIndex(
            model_name='marketmodel',
            index=models.Index(fields=['category_slug', 'item_type', 'brand', 'name'], name='listings_ma_categor_6540b6_idx'),
        ),
        migrations.AddIndex(
            model_name='marketmodel',
            index=models.Index(fields=['brand', 'name'], name='listings_ma_brand_i_69c88d_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketmodel',
            constraint=models.UniqueConstraint(fields=('brand', 'category_slug', 'item_type', 'name'), name='market_model_unique_scope'),
        ),
        migrations.DeleteModel(
            name='VehicleModel',
        ),
    ]
