# Generated by Django 5.0.4 on 2026-06-11 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_market_taxonomy_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicslisting',
            name='brand_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronics_listings', to='listings.marketbrand'),
        ),
        migrations.AlterField(
            model_name='electronicslisting',
            name='model_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronics_listings', to='listings.marketmodel'),
        ),
        migrations.AlterField(
            model_name='motorcyclelisting',
            name='brand_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motorcycle_listings', to='listings.marketbrand'),
        ),
        migrations.AlterField(
            model_name='motorcyclelisting',
            name='model_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motorcycle_listings', to='listings.marketmodel'),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='brand_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_listings', to='listings.marketbrand'),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='model_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_listings', to='listings.marketmodel'),
        ),
    ]
