# Generated by Django 5.2.13 on 2026-04-07 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_threads', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='thread',
            name='participant_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads_as_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='participant_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads_as_b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.thread'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['participant_a', 'participant_b'], name='chat_thread_partici_2c5549_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['-updated_at'], name='chat_thread_updated_d607ba_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'created_at'], name='chat_messag_thread__9895ae_idx'),
        ),
    ]
